language: php
sudo: required
services:
 - mysql
addons:
 postgresql: "9.6"
 apt:
  packages:
   - openjdk-8-jre-headless

cache:
 directories:
  - $HOME/.composer/cache
  - $HOME/.npm
php:
 - 7.2

env:
 global:
  - MOODLE_BRANCH=MOODLE_37_STABLE

 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
 - phpenv config-rm xdebug.ini
 - nvm install 14
 - nvm use 14
 - cd ../..
 - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
 - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install --no-init

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
